# Back_end FLASK > API Rest's Routes
from flask import Flask, jsonify, request
from flask_cors import CORS
from database import init_db, get_connection

# Create an Flash's application instance
app = Flask(__name__, static_folder='static', static_url_path='')

# Habilitate CORS
CORS(app)

# Route Nº1 - Initial screen
@app.route('/')

def index():
    #FEED INDEX.HTML FILE IN STATIC FOLDER
    return app.send_static_file('index.html')

# Route Nº2 - API STATUS
@app.route('/status')
def status():
    '''
    API's VERIFICATION ROUTE (HEALTH)
    Returns JSON informing  server's active state
    '''

    return jsonify({
        "status": "online",
        "system": "Order System's Production",
        "version": "1.0.0",
        "message": "Hello Factory, API working!"
    })

#Route Nº3 - List all orders (GET)
@app.route('/orders', methods=['GET'])

def list_orders():
    '''
    LIST ALL REGISTEREDF PRODUCTION ORDERS
    METHODS HTTP: GET
    URL: https://localhost:5000/orders
    Returns: Orders and list in JSON format
    '''
    
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute('SELECT * FROM orders ORDER BY id DESC')
    orders = cursor.fetchall()
    conn.close()
    
    # Converts every SQLite Row in Python dictionary to serialize in JSOn
    return jsonify([dict(o) for o in orders])

# ── ROUTE: Get a specific order by ID (GET) ────────
@app.route('/orders/<int:order_id>', methods=['GET'])
def search_order(order_id):
    """
    Search an unic production order.
    URL parametersL:
        order_id (int): ID of the order to be searched.
    Returns:
        200 + JSON of order, if found it.
        404 + error message, if not exist.
    """
    conn = get_connection()
    cursor = conn.cursor()
    
    # The '?' switchs the id in safely way
    cursor.execute('SELECT * FROM orders WHERE id = ?', (order_id,))
    order = cursor.fetchone() # fetchone() returns an unic register or none
    conn.close()
    
    # Se o ID nao existir, retornamos 404
    if order is None:
        return jsonify({'error': f'Order {order_id} not found.'}), 404
    return jsonify(dict(order)), 200

# ── ROUTE: Create a new order (POST) ──────────────
@app.route('/orders', methods=['POST'])
def create_order():
    """
    Create a new production order from sended JSON data 
    
    Spected body (JSON):
        product (str): Product Name, Obligatory
        quantity (int): Pieces quantity. Obligatory, > 0.
        status (str): Optional. Standard: 'Pendent'.
    Returns:
        201 + Created JSON order, in successfully cases.
        400 + error message, if invalid data.
    """
    data = request.get_json()
    # ── Input validation ───────────────────────────────
    
    # Verify if body was sended and the JSON is valid
    if not data:
        return jsonify({'error': 'Missing or invalid request body.'}), 400
    
    # Verify obligatory field 'product'
    product = data.get('product', '').strip()
    if not product:
        return jsonify({'error': 'Field "product" its obligatory and cannot be empty.'}), 400
    
    # Verify obligatory field 'quantity'
    quantity = data.get('quantity')
    if quantity is None:
        return jsonify({'error': 'Field "quantity" its obligatory and cannot be empty.'}), 400
    
    # Verify if quantity is a positive number
    try:
        quantity = int(quantity)
        if quantity <= 0:
            raise ValueError()
    except (ValueError, TypeError):
        return jsonify({'error': 'Field "quantity" must be a positive number.'}), 400
    
    # Status it's optional; use 'Pendent' if not informed
    validate_status = ['Pendent', 'In progress', 'Conclused']
    status = data.get('status', 'Pendent')
    if status not in validate_status:
        return jsonify({'error': f'Invalid status. Use: {validate_status}'}), 400
    
    # ── Database insert ───────────────────────────────────
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute(
    'INSERT INTO orders (product, quantity, status) VALUES (?, ?, ?)', (product, quantity, status))
    conn.commit()
    
    # We get the ID automatic generated by the database
    new_id = cursor.lastrowid
    conn.close()
    # We search the new-born register to return
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute('SELECT * FROM orders WHERE id = ?', (new_id,))
    new_order = cursor.fetchone()
    conn.close()
    # Returns 201 Created with complete register
    return jsonify(dict(new_order)), 201

# STARTING POINT
if __name__== '__main__':
    init_db()
    
    app.run(debug=True, host='0.0.0.0', port=5000)