# Back_end FLASK > API Rest's Routes
from flask import Flask, jsonify, request
from flask_cors import CORS
from database import init_db, get_connection

# Create an Flash's application instance
app = Flask(__name__, static_folder='static', static_url_path='')

# Habilitate CORS
CORS(app)

# Route Nº1 - Initial screen
@app.route('/')

def index():
    #FEED INDEX.HTML FILE IN STATIC FOLDER
    return app.send_static_file('index.html')

# Route Nº2 - API STATUS
@app.route('/status')
def status():
    '''
    API's VERIFICATION ROUTE (HEALTH)
    Returns JSON informing  server's active state
    '''

    return jsonify({
        "status": "online",
        "system": "Order System's Production",
        "version": "1.0.0",
        "message": "Hello Factory, API working!"
    })

#Route Nº3 - List all orders (GET)
@app.route('/orders', methods=['GET'])

def list_orders():
    '''
    LIST ALL REGISTEREDF PRODUCTION ORDERS
    METHODS HTTP: GET
    URL: https://localhost:5000/orders
    Returns: Orders and list in JSON format
    '''
    
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute('SELECT * FROM orders ORDER BY id DESC')
    orders = cursor.fetchall()
    conn.close()
    
    # Converts every SQLite Row in Python dictionary to serialize in JSOn
    return jsonify([dict(o) for o in orders])

# ── ROUTE: Get a specific order by ID (GET) ────────
@app.route('/orders/<int:order_id>', methods=['GET'])
def search_order(order_id):
    """
    Search an unic production order.
    URL parametersL:
        order_id (int): ID of the order to be searched.
    Returns:
        200 + JSON of order, if found it.
        404 + error message, if not exist.
    """
    
    conn = get_connection()
    cursor = conn.cursor()
    
    # The '?' switchs the id in safely way
    cursor.execute('SELECT * FROM orders WHERE id = ?', (order_id,))
    order = cursor.fetchone() # fetchone() returns an unic register or none
    conn.close()
    
    # Se o ID nao existir, retornamos 404
    if order is None:
        return jsonify({'error': f'Order {order_id} not found.'}), 404
    return jsonify(dict(order)), 200

# ── ROUTE: Create a new order (POST) ──────────────
@app.route('/orders', methods=['POST'])
def create_order():
    """
    Create a new production order from sended JSON data 
    
    Spected body (JSON):
        product (str): Product Name, Obligatory
        quantity (int): Pieces quantity. Obligatory, > 0.
        status (str): Optional. Standard: 'Pending'.
    Returns:
        201 + Created JSON order, in successfully cases.
        400 + error message, if invalid data.
    """
    
    data = request.get_json()
    # ── Input validation ───────────────────────────────
    
    # Verify if body was sended and the JSON is valid
    if not data:
        return jsonify({'error': 'Missing or invalid request body.'}), 400
    
    # Verify obligatory field 'product'
    product = data.get('product', '').strip()
    if not product:
        return jsonify({'error': 'Field "product" its obligatory and cannot be empty.'}), 400
    
    # Verify obligatory field 'quantity'
    quantity = data.get('quantity')
    if quantity is None:
        return jsonify({'error': 'Field "quantity" its obligatory and cannot be empty.'}), 400
    
    # Verify if quantity is a positive number
    try:
        quantity = int(quantity)
        if quantity <= 0:
            raise ValueError()
    except (ValueError, TypeError):
        return jsonify({'error': 'Field "quantity" must be a positive number.'}), 400
    
    # Status it's optional; use 'Pending' if not informed
    valid_status = ['Pending', 'In progress', 'Complete']
    status = data.get('status', 'Pending')
    if status not in valid_status:
        return jsonify({'error': f'Invalid status. Use: {valid_status}'}), 400
    
    # ── Database insert ───────────────────────────────────
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute(
    'INSERT INTO orders (product, quantity, status) VALUES (?, ?, ?)', (product, quantity, status))
    conn.commit()
    
    # We get the ID automatic generated by the database
    new_id = cursor.lastrowid
    conn.close()
    
    # We search the new-born register to return
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute('SELECT * FROM orders WHERE id = ?', (new_id,))
    new_order = cursor.fetchone()
    conn.close()
    
    # Returns 201 Created with complete register
    return jsonify(dict(new_order)), 201

# ── ROUTE: Order status update (PUT) ───────────────
@app.route('/orders/<int:order_id>', methods=['PUT'])
def update_order(order_id):
    """
    Update an existent production order
    URL parameters:
        order_id (int): ID of order and update.
        Spected body (JSON):
        status (str): New status. Accepted values:
        'Pending', 'In progress', 'Complete'.
    Returns:
        200 + JSON updated order.
        400 + error if invalid status.
        404 + error if order not found.
    """
    
    data = request.get_json()
    if not data:
        return jsonify({'error': 'Missing or invalid request body.'}), 400
    
    # Verify status field
    valid_status = ['Pending', 'In progress', 'Complete']
    new_status = data.get('status', '').strip()
    if not new_status:
        return jsonify({'error': 'Field "status" is obligatory.'}), 400
    if new_status not in valid_status:
        return jsonify({'error': f'Invalid status. Allowed values: {valid_status}'}), 400
    conn = get_connection()
    cursor = conn.cursor()
    
    # Verify existent order before try visualize it 
    cursor.execute('SELECT id FROM orders WHERE id = ?', (order_id,))
    if cursor.fetchone() is None:
        conn.close()
        return jsonify({'error': f'Order {order_id} not found.'}),404
    # Update
    cursor.execute(
        'UPDATE orders SET status = ? WHERE id = ?', (new_status, order_id))
    conn.commit()
    conn.close()
    # Return the updated register
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute('SELECT * FROM orders WHERE id = ?', (order_id,))
    updated_order = cursor.fetchone()
    conn.close()
    return jsonify(dict(updated_order)), 200

# ── ROUTE: Remove an order (DELETE) ───────────────────────
@app.route('/orders/<int:order_id>', methods=['DELETE'])
def remove_order(order_id):
    """
    Remove permanently an order searched by ID
    URL parameters:
        order_id (int): removed ID order
    Returns:
        200 + confirmation message.
        404 + error if order not found.
    """
    
    conn = get_connection()
    cursor = conn.cursor()
    # Verify the existance before DELETE
    cursor.execute('SELECT id, product FROM orders WHERE id = ?',(order_id,))
    order = cursor.fetchone()
    if order is None:
        conn.close()
        return jsonify({'error': f'Order {order_id} not found.'}), 404

    # Save the prodcut name to use in confirmation message
    name_product = order['product']
    
    # Remove
    cursor.execute('DELETE FROM orders WHERE id = ?', (order_id,))
    conn.commit()
    conn.close()
    return jsonify({
        'message': f'Order {order_id} ({name_product}) removed with success.', 'id_removed': order_id}), 200

# STARTING POINT
if __name__== '__main__':
    init_db()
    
    app.run(debug=True, host='0.0.0.0', port=5000)